export const SET_AUTHORIZED = "SET_AUTHORIZED";
export const SET_UNAUTHORIZED = "SET_UNAUTHORIZED";
export const SET_USER_DATA = "SET_USER_DATA";
export const UNSET_USER_DATA = "UNSET_USER_DATA";
export const SET_MACHINES_DATA = "SET_MACHINES_DATA";
export const UPDATE_MACHINE_DATA = "UPDATE_MACHINE_DATA";
export const UNSET_MACHINES_DATA = "UNSET_MACHINES_DATA";